<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
 <PropertyGroup>
  <Configuration Condition="'$(Configuration)' == ''">Release</Configuration><Platform Condition="'$(Platform)' == ''">x64</Platform>
  <OutputType>WinExe</OutputType><TargetFrameworkVersion>v4.8</TargetFrameworkVersion><PlatformTarget>x64</PlatformTarget>
  <AssemblyName>Bluetooth Renamer</AssemblyName><RootNamespace>BluetoothRenamer</RootNamespace><OutputPath>bin\</OutputPath>
  <ApplicationManifest>src\app.manifest</ApplicationManifest><ApplicationIcon>src\App.ico</ApplicationIcon><AppConfig>src\App.config</AppConfig>
  <Optimize>true</Optimize><LangVersion>5</LangVersion><GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
 </PropertyGroup>
 <ItemGroup>
  <Reference Include="System"/><Reference Include="System.Core"/><Reference Include="System.Runtime.Serialization"/><Reference Include="System.Xml"/><Reference Include="System.Xaml"/>
  <Reference Include="WindowsBase"/><Reference Include="PresentationCore"/><Reference Include="PresentationFramework"/>
  <Compile Include="src\*.cs"/>
  <EmbeddedResource Include="src\MainWindow.xaml"><LogicalName>MainWindow.xaml</LogicalName></EmbeddedResource>
  <EmbeddedResource Include="src\App.ico"><LogicalName>App.ico</LogicalName></EmbeddedResource>
 </ItemGroup>
 <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>
</Project>
